#!/bin/bash

DIR="$( cd "$( dirname "$0" )" > /dev/null; pwd )"
ORN="$DIR/ornament"

CSS_BASE="$ORN/lib/generators/ornament/templates/app/assets/stylesheets"
CSS_VENDOR="$ORN/lib/generators/ornament/templates/vendor/assets/stylesheets"
CSS_SETTINGS="$ORN/test/dummy/app/assets/stylesheets/_settings.scss"

JS_BASE="$ORN/lib/generators/ornament/templates/app/assets/javascripts"
JS_VENDOR="$ORN/lib/generators/ornament/templates/vendor/assets/javascripts"

#
# pull the latest ornament in
#

git clone git@github.com:katalyst/ornament.git ornament

#
# install grunt modules
#

echo "Installing node dependancies..."
npm install grunt-cli
npm install

#
# move CSS over to new CSS folder
#

echo "Copying CSS..."
mv "$CSS_BASE" "$DIR/css"
mv "$CSS_VENDOR" "$DIR/css/vendor"
mv "$CSS_SETTINGS" "$DIR/css/$1"

#
# move JS over to new JS folder
#

echo "Copying JS..."
mv "$JS_BASE" "$DIR/js"
mv "$JS_VENDOR" "$DIR/js/vendor"

#
# remove railsy .js files
# these files only have //= require statements in them
#

echo "Removing unnecessary JS..."
rm "$DIR/js/ornament/core.js"
rm "$DIR/js/application.js"
rm "$DIR/js/application_bottom.js"

# #
# # rename css from .css.scss to .scss
# #

# echo "Renaming CSS files..."
# for files in css/*.scss css/**/*.scss css/**/**/*.scss
# do
#   mv "$files" "${files%.scss}.scss"
# done

#
# copy over image assets
#

echo "Copying image assets..."
mv "$ORN/lib/generators/ornament/templates/app/assets/images" "$DIR/images"
mv "$ORN/lib/generators/ornament/templates/app/assets/icons" "$DIR/icons"

#
# copy over html file
#

echo "Copying HTML files..."
mkdir "$DIR/inc"
mv "$ORN/lib/generators/ornament/templates/app/views/layouts/global.html.erb" "$DIR/index.html"
mv "$ORN/lib/generators/ornament/templates/app/views/layouts/_webfonts.html.erb" "$DIR/inc/_webfonts.html"

echo "HTML files successfully copied, running ornament patch..."
grunt ornament_patch
echo "Ornament HTML patch completed."

#
# download jquery
#

echo "Download latest jQuery..."
curl -s "http://code.jquery.com/jquery.js" > "$DIR/js/vendor/jquery.js"

#
# building JS and CSS via grunt 
#

echo "Building JS and CSS for first time using grunt..."
grunt css
grunt js

#
# remove static-site git files
#

rm -rf .git
rm -rf .gitignore

#
# create a new gitignore file
#

echo node_modules > .gitignore
echo .sass-cache >> .gitignore

#
# delete ornament folder
#

echo "Cleaning up ornament folder"
rm -rf ornament

#
# remove this file
#

rm -rf ./orn_rename

#
# open the index file
#

open index.html

#
# re-initing git
#

git init
git add .
git commit -m "Initial commit"